### PR TITLE
Use configdir

### PR DESCRIPTION
**Pull request by haaawk**
Refs https://github.com/tursodatabase/turso-cli/issues/876

### CODE REVIEW

**Review by athoscouto — APPROVED** [review]

**Comment by avinassh** [comment]
Does this break history for existing users?

**Comment by athoscouto** [comment]
It does, do you think it is worth it to migrate? I'm OK with breaking it just once

**Comment by haaawk** [comment]
> Does this break history for existing users?

It does but I'm aware and happy to make the sacrifice.

**Comment by avinassh** [comment]
Fine by me too. I just wanted to confirm.

**Review by avinassh — APPROVED** [review]

**Pull request merged**
